os: linux
language: node_js
node_js:
  - "18"
dist: focal
script:
  - npm run build
  - echo "Commit sha - $TRAVIS_COMMIT"
  - mkdir -p dist/@thawkin3/root-config/$TRAVIS_COMMIT
  - mv dist/*.* dist/@thawkin3/root-config/$TRAVIS_COMMIT/
deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: "single-spa-portfolio"
  region: "us-east-2"
  cache_control: "max-age=31536000"
  acl: "public_read"
  local_dir: dist
  cleanup: false
  on:
    branch: main
